# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ccffb7d7d69a2364f07e948a9efbcc48f273631dd03f388fc37220b57c23bb0d1d957c6d8bdf6b00c816cc604dcea5741ab30846128786c4fe82a86b0fc56cc

test:
  secret_key_base: 9f2c49071d33782a980af52ec50aef602d3213788c406c41a17be3e24fe2c3781bd34f2971e9aaca2627e02747f8571708ee9b6005f2eda33f59bbd41f4ffec6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
